apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo
spec:
  selector:
    matchLabels:
      app: k8sdemo
  replicas: 3
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers:
        - name: k8sdemo
          image: cfaife/k8sdemo
          ports:
            - containerPort: 8080

