apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-service
spec:
  selector:
    app: k8sdemo
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  externalIPs:
  - 192.168.100.7